### ISSUE TITLE
Assignment 1 ready for grading - Summer Liu

### ISSUE THREAD

**Issue by SummerLiuxx** [VIS-2129-F2020/summerliu-vis#1]
https://vis-2129-f2020.github.io/summerliu-vis/1st-Assignment.html

My first assignment is ready for grading, thank you for your help! Please let me know how I can improve!

**Comment by bauranov** [comment]
Great work! Here are my comments:
- Line 17: Move this chunk to line 6 to avoid messages in HTML.
- Line 22 (and all other lines with headers): add one space between # and text to format the headers properly.
- Plot 6: it makes sense to exclude outliers above 200k so the other boxes would be more legible. Avoid scientific notation. There are several ways to change from scientific to regular notation. Take a look at [this website](https://stackoverflow.com/questions/14563989/force-r-to-stop-plotting-abbreviated-axis-labels-e-g-1e00-in-ggplot2) on how to do that.
- Plot 7: Change the axes' names; AGEP, and PINCP are not very good descriptions of the data. This applies to all plots.

You are making really good progress, keep up the good work!
